CREATE SEQUENCE SEQ_MOTORISTAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VEICULOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ROTAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VIAGENS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CLIENTES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ENTREGAS START WITH 1 INCREMENT BY 1;


INSERT INTO USR_LOGISTICA.MOTORISTAS (MOTORISTA_ID, NOME, CNH, TELEFONE)
VALUES (SEQ_MOTORISTAS.NEXTVAL, 'Eliel Martins', '1234567890', '11999999999');
INSERT INTO USR_LOGISTICA.MOTORISTAS (MOTORISTA_ID, NOME, CNH, TELEFONE)
VALUES (SEQ_MOTORISTAS.NEXTVAL, 'Raphaela Teles', '0987654321', '11988888888');
INSERT INTO USR_LOGISTICA.MOTORISTAS (MOTORISTA_ID, NOME, CNH, TELEFONE)
VALUES (SEQ_MOTORISTAS.NEXTVAL, 'Alexandre Moraes', '1122334455', '11977777777');
INSERT INTO USR_LOGISTICA.MOTORISTAS (MOTORISTA_ID, NOME, CNH, TELEFONE)
VALUES (SEQ_MOTORISTAS.NEXTVAL, 'Leonardo Paulo', '6677889900', '11966666666');
INSERT INTO USR_LOGISTICA.MOTORISTAS (MOTORISTA_ID, NOME, CNH, TELEFONE)
VALUES (SEQ_MOTORISTAS.NEXTVAL, 'André Pimenta', '5544332211', '11955555555');


INSERT INTO USR_LOGISTICA.VEICULOS (VEICULO_ID, PLACA, MODELO, CAPACIDADE_CARGA, STATUS)
VALUES (SEQ_VEICULOS.NEXTVAL, 'ABC1234', 'Caminhão Baú', 5000, 'Disponível');
INSERT INTO USR_LOGISTICA.VEICULOS (VEICULO_ID, PLACA, MODELO, CAPACIDADE_CARGA, STATUS)
VALUES (SEQ_VEICULOS.NEXTVAL, 'DEF5678', 'Van', 2000, 'Manutenção');
INSERT INTO USR_LOGISTICA.VEICULOS (VEICULO_ID, PLACA, MODELO, CAPACIDADE_CARGA, STATUS)
VALUES (SEQ_VEICULOS.NEXTVAL, 'GHI9012', 'Caminhão Tanque', 7000, 'Disponível');
INSERT INTO USR_LOGISTICA.VEICULOS (VEICULO_ID, PLACA, MODELO, CAPACIDADE_CARGA, STATUS)
VALUES (SEQ_VEICULOS.NEXTVAL, 'JKL3456', 'Caminhão Carga Seca', 8000, 'Indisponível');
INSERT INTO USR_LOGISTICA.VEICULOS (VEICULO_ID, PLACA, MODELO, CAPACIDADE_CARGA, STATUS)
VALUES (SEQ_VEICULOS.NEXTVAL, 'MNO7890', 'Carreta', 15000, 'Disponível');


INSERT INTO USR_LOGISTICA.ROTAS (ROTA_ID, ORIGEM, DESTINO, DISTANCIA)
VALUES (SEQ_ROTAS.NEXTVAL, 'São Paulo', 'Rio de Janeiro', 430.5);
INSERT INTO USR_LOGISTICA.ROTAS (ROTA_ID, ORIGEM, DESTINO, DISTANCIA)
VALUES (SEQ_ROTAS.NEXTVAL, 'São Paulo', 'Belo Horizonte', 586.7);
INSERT INTO USR_LOGISTICA.ROTAS (ROTA_ID, ORIGEM, DESTINO, DISTANCIA)
VALUES (SEQ_ROTAS.NEXTVAL, 'Curitiba', 'Porto Alegre', 712.3);
INSERT INTO USR_LOGISTICA.ROTAS (ROTA_ID, ORIGEM, DESTINO, DISTANCIA)
VALUES (SEQ_ROTAS.NEXTVAL, 'Brasília', 'Goiânia', 209.8);
INSERT INTO USR_LOGISTICA.ROTAS (ROTA_ID, ORIGEM, DESTINO, DISTANCIA)
VALUES (SEQ_ROTAS.NEXTVAL, 'Salvador', 'Recife', 806.4);


INSERT INTO USR_LOGISTICA.VIAGENS (VIAGEM_ID, VEICULO_ID, MOTORISTA_ID, ROTA_ID, DATA_PARTIDA, DATA_CHEGADA, STATUS)
VALUES (SEQ_VIAGENS.NEXTVAL, 1, 1, 1, TO_DATE('2024-12-01', 'YYYY-MM-DD'), TO_DATE('2024-12-02', 'YYYY-MM-DD'), 'Concluída');
INSERT INTO USR_LOGISTICA.VIAGENS (VIAGEM_ID, VEICULO_ID, MOTORISTA_ID, ROTA_ID, DATA_PARTIDA, DATA_CHEGADA, STATUS)
VALUES (SEQ_VIAGENS.NEXTVAL, 2, 2, 2, TO_DATE('2024-12-03', 'YYYY-MM-DD'), NULL, 'Em andamento');
INSERT INTO USR_LOGISTICA.VIAGENS (VIAGEM_ID, VEICULO_ID, MOTORISTA_ID, ROTA_ID, DATA_PARTIDA, DATA_CHEGADA, STATUS)
VALUES (SEQ_VIAGENS.NEXTVAL, 3, 3, 3, TO_DATE('2024-12-04', 'YYYY-MM-DD'), TO_DATE('2024-12-05', 'YYYY-MM-DD'), 'Concluída');
INSERT INTO USR_LOGISTICA.VIAGENS (VIAGEM_ID, VEICULO_ID, MOTORISTA_ID, ROTA_ID, DATA_PARTIDA, DATA_CHEGADA, STATUS)
VALUES (SEQ_VIAGENS.NEXTVAL, 4, 4, 4, TO_DATE('2024-12-01', 'YYYY-MM-DD'), NULL, 'Cancelada');
INSERT INTO USR_LOGISTICA.VIAGENS (VIAGEM_ID, VEICULO_ID, MOTORISTA_ID, ROTA_ID, DATA_PARTIDA, DATA_CHEGADA, STATUS)
VALUES (SEQ_VIAGENS.NEXTVAL, 5, 5, 5, TO_DATE('2024-12-02', 'YYYY-MM-DD'), TO_DATE('2024-12-04', 'YYYY-MM-DD'), 'Concluída');


INSERT INTO USR_LOGISTICA.CLIENTES (CLIENTE_ID, NOME, TELEFONE, EMAIL, ENDERECO)
VALUES (SEQ_CLIENTES.NEXTVAL, 'Empresa A', '11912345678', 'contato@empresaA.com.br', 'Rua A, São Paulo');
INSERT INTO USR_LOGISTICA.CLIENTES (CLIENTE_ID, NOME, TELEFONE, EMAIL, ENDERECO)
VALUES (SEQ_CLIENTES.NEXTVAL, 'Empresa B', '11987654321', 'contato@empresaB.com.br', 'Avenida B, Rio de Janeiro');
INSERT INTO USR_LOGISTICA.CLIENTES (CLIENTE_ID, NOME, TELEFONE, EMAIL, ENDERECO)
VALUES (SEQ_CLIENTES.NEXTVAL, 'Empresa C', '11911223344', 'contato@empresaC.com.br', 'Rua C, Belo Horizonte');
INSERT INTO USR_LOGISTICA.CLIENTES (CLIENTE_ID, NOME, TELEFONE, EMAIL, ENDERECO)
VALUES (SEQ_CLIENTES.NEXTVAL, 'Empresa D', '11955667788', 'contato@empresaD.com.br', 'Rua D, Salvador');
INSERT INTO USR_LOGISTICA.CLIENTES (CLIENTE_ID, NOME, TELEFONE, EMAIL, ENDERECO)
VALUES (SEQ_CLIENTES.NEXTVAL, 'Empresa E', '11999887766', 'contato@empresaE.com.br', 'Rua E, Recife');


INSERT INTO USR_LOGISTICA.ENTREGAS (ENTREGA_ID, VIAGEM_ID, CLIENTE_ID, ENDERECO_ENTREGA, STATUS)
VALUES (SEQ_ENTREGAS.NEXTVAL, 1, 1, 'Rua A, São Paulo', 'Entregue');
INSERT INTO USR_LOGISTICA.ENTREGAS
