CREATE USER USR_LOGISTICA IDENTIFIED BY 1234;

GRANT CONNECT, RESOURCE TO USR_LOGISTICA;
GRANT UNLIMITED TABLESPACE TO USR_LOGISTICA;

CREATE TABLE USR_LOGISTICA.MOTORISTAS (
    MOTORISTA_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    CNH VARCHAR2(20) NOT NULL,
    TELEFONE VARCHAR2(15),
    CONSTRAINT PK_MOTORISTAS PRIMARY KEY (MOTORISTA_ID)
);

CREATE TABLE USR_LOGISTICA.VEICULOS (
    VEICULO_ID NUMBER NOT NULL,
    PLACA VARCHAR2(10) NOT NULL,
    MODELO VARCHAR2(100),
    CAPACIDADE_CARGA NUMBER(10, 2),
    STATUS VARCHAR2(50),
    CONSTRAINT PK_VEICULOS PRIMARY KEY (VEICULO_ID)
);

CREATE TABLE USR_LOGISTICA.ROTAS (
    ROTA_ID NUMBER NOT NULL,
    ORIGEM VARCHAR2(100),
    DESTINO VARCHAR2(100),
    DISTANCIA NUMBER(10, 2),
    CONSTRAINT PK_ROTAS PRIMARY KEY (ROTA_ID)
);

CREATE TABLE USR_LOGISTICA.VIAGENS (
    VIAGEM_ID NUMBER NOT NULL,
    VEICULO_ID NUMBER NOT NULL,
    MOTORISTA_ID NUMBER NOT NULL,
    ROTA_ID NUMBER,
    DATA_PARTIDA DATE,
    DATA_CHEGADA DATE,
    STATUS VARCHAR2(50),
    CONSTRAINT PK_VIAGENS PRIMARY KEY (VIAGEM_ID),
    CONSTRAINT FK_VIAGENS_VEICULOS FOREIGN KEY (VEICULO_ID) REFERENCES USR_LOGISTICA.VEICULOS (VEICULO_ID),
    CONSTRAINT FK_VIAGENS_MOTORISTAS FOREIGN KEY (MOTORISTA_ID) REFERENCES USR_LOGISTICA.MOTORISTAS (MOTORISTA_ID),
    CONSTRAINT FK_VIAGENS_ROTAS FOREIGN KEY (ROTA_ID) REFERENCES USR_LOGISTICA.ROTAS (ROTA_ID)
);

CREATE TABLE USR_LOGISTICA.CLIENTES (
    CLIENTE_ID NUMBER NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    TELEFONE VARCHAR2(15) NOT NULL,
    EMAIL VARCHAR2(100),
    ENDERECO VARCHAR2(255) NOT NULL,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (CLIENTE_ID)
);

CREATE TABLE USR_LOGISTICA.ENTREGAS (
    ENTREGA_ID NUMBER NOT NULL,
    VIAGEM_ID NUMBER NOT NULL,
    CLIENTE_ID NUMBER NOT NULL,
    ENDERECO_ENTREGA VARCHAR2(255),
    STATUS VARCHAR2(50),
    CONSTRAINT PK_ENTREGAS PRIMARY KEY (ENTREGA_ID),
    CONSTRAINT FK_ENTREGAS_VIAGENS FOREIGN KEY (VIAGEM_ID) REFERENCES USR_LOGISTICA.VIAGENS (VIAGEM_ID),
    CONSTRAINT FK_ENTREGAS_CLIENTES FOREIGN KEY (CLIENTE_ID) REFERENCES USR_LOGISTICA.CLIENTES (CLIENTE_ID)
);
